name: private_memo
description: A lightweight mobile application for secure personal memos.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Local database
  sqflite: ^2.3.0
  path: ^1.9.0

  # Map (OpenStreetMap)
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  # Location service
  geolocator: ^10.1.0

  shared_preferences: ^2.2.3

  http: ^1.2.0

  audioplayers: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/black.mp3
